# Model config with interpolation
# Change num_heads here → all nested configs update automatically

num_heads: 2
embedding_dim: 32
head_embedding_dim: 8
n_layers: 4
input_dim: 1
dropout: 0.1
dtype: bfloat16

training:
  quantiles: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  learning_rate: 1e-3
  weight_decay: 0.0
  batch_size: 32

output_dim: 9  # = len(quantiles)

weaving_block:
  embedding_dim: ${head_embedding_dim}
  num_heads: ${num_heads}
  n_layers: ${n_layers}
  
  layer:
    embedding_dim: ${head_embedding_dim}
    num_heads: ${num_heads}
    dropout: ${dropout}
    dtype: ${dtype}
    conv1d_kernel_size: 4
    qkv_proj_blocksize: 4
    bias: false
    
    mlstm_cell:
      embedding_dim: ${head_embedding_dim}
      num_heads: ${num_heads}
      dtype: ${dtype}
